<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Envanta.Infrastructure\Envanta.Infrastructure.csproj" />
    <ProjectReference Include="..\Envanta.SoapApi\Envanta.SoapApi.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
